messages:
  prefix: "&6[&cyAuth&6] "
  no-permission: "&aNie posiadasz uprawnien."
  no-console: "&aNie mozna uzywac tej komendy w consoli."
  login-required-e: "&aAby sie zalogowac wpisz: &c/login <haslo>"
  login-required-first: "&aUps, wyglada na to, ze twoje IP sie zmienilo. Zaloguj sie: &c/login <haslo>"
  register-required: "&aUps, wyglada na to, ze musisz sie zarejestrowac: &c/register <haslo> <haslo>"
  register-help: "&aUps, nieprawidlowe uzycie. Sprobuj: &c/register <haslo> <haslo>"
  register-success: "&aPomyslnie zarejestrowales sie, uzywajac hasla: &c%password%"
  already-registered: "&aPrzepraszamy, juz sie zarejestrowales."
  register-invalid: "&aNiestety, oba hasla musza byc takie same."
  already-logged: "&aHej! Juz sie zalogowales."
  login-help: "&aUps, nieprawidlowe uzycie. Sprobuj: &c/login <haslo>"
  login-wrong: "&aUps, to nie jest prawidlowe haslo. Czy to napewno ty?"
  login-success: "&aPomyslnie zalogowano!"