name: yAuth
version: 1.3
author: Yamesiak
main: pl.yamesiak.register.Register
commands:
  register:
    description: Komenda na zarejestrowanie sie
    usage: /register <haslo> <haslo>
  login:
    description: Komenda na zalogowanie sie
    usage: /login <haslo>